import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import "./globals.css";
import { ToastProvider } from "./providers/SonnerProviders";
import TanstackProvider from "./providers/TanStackProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-backGroundDark  text-slate-100 px-2 py-4 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <TanstackProvider>
            <SessionProvider>{children}</SessionProvider>
          </TanstackProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
